---
          - name: download consul zip file
            get_url:
                    url: https://releases.hashicorp.com/consul/1.2.2/consul_1.2.2_linux_amd64.zip
                    dest: /usr/local/bin/
          - name: Install dependencies
            package:
                    name: "{{ item }}"
                    state: latest
            with_items:
                    - unzip
          - name: unzip the file
            unarchive:
                    src: /usr/local/bin/consul_1.2.2_linux_amd64.zip
                    dest: /usr/local/bin/
                    remote_src: yes

          - name: create folder for data dir
            file:
                    path: /var/consul
                    state: directory
                    mode: '0777'
          - name: create folder for config file
            file:
                    path: "{{item.dest}}"
                    state: directory
                    mode: '{{item.mode}}'
            with_items:
                    - { dest: '/etc/consul.d', mode: '0777'}
                    - { dest: '/etc/consul.d/scripts', mode: '0777'}
    
          - name: remove the zip file
            file:
                    path: /usr/local/bin/consul_1.2.2_linux_amd64.zip
                    state: absent


          - debug:
                 msg: "{{ inventory_hostname }}"
          - debug:
                  msg: "{{ groups['master'] }}"

          - name: generate consul key in consul1
            when: inventory_hostname == 'consul1'
            shell: "consul keygen"
            register: consul_key
          - debug:
                  msg: " {{ consul_key }}"
                  #loop: "{{ consul_key.results }}"

          - name: configure bootstrap and add consul key in config
            #when: inventory_hostname == 'consul3'
            # shell: "consul keygen"
            #          register: consul_key
            template:
                    src: config.json
                    dest: /etc/consul.d/
          - debug:
                  msg: "{{ inventory_hostname }}"
         
          - name: copy file from host 1 to host 2&3
            shell: "scp -o StrictHostKeyChecking=no  ansible@172.31.44.192/etc/consul.d/config.json ansible@172.31.18.93:/etc/consul.d/"

          - name: service file for consul
            template:
                    src: consul.service
                    dest: /etc/systemd/system/



